import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseManaboxCsvContent } from "../csv-parser";

/**
 * Phase 22-02 Task 2 (D-07): perf pin for the Manabox CSV parser.
 *
 * HARD-03 first clause: parsing the operator's full 12,749-row export must
 * complete in under 2 seconds on the runner machine. The fixture is
 * generated by `scripts/generate-large-fixture.ts` (D-08) — synthetic data
 * (NOT the operator's real export per Phase 17 D-11 privacy) with the
 * canonical Phase 17 column shape.
 *
 * Path resolution: the fixture lives at `<repo-root>/test-fixtures/large-export.csv`.
 * From this test file, that's three levels up (__tests__/ → lib/ → src/ →
 * repo root → test-fixtures/). We use `import.meta.dirname` (Node 20+ via
 * @types/node@^20) for the __dirname equivalent under ESM.
 *
 * Default-run: this test is NOT env-gated and NOT skipped. It runs as part
 * of the standard `npm test` invocation so any parser-perf regression
 * surfaces immediately.
 */

const FIXTURE_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "test-fixtures",
  "large-export.csv",
);

describe("parseManaboxCsvContent — perf pin (HARD-03)", () => {
  it("parses 12,749-row Manabox CSV in under 2 seconds", () => {
    // Read the fixture from disk. If it's missing, fail clearly with a
    // pointer to the generator script (rather than silently passing).
    let csv: string;
    try {
      csv = readFileSync(FIXTURE_PATH, "utf-8");
    } catch (err) {
      throw new Error(
        `Missing fixture at ${FIXTURE_PATH}. Regenerate via: ` +
          `npx tsx scripts/generate-large-fixture.ts. Underlying error: ` +
          (err instanceof Error ? err.message : String(err)),
      );
    }

    const t0 = performance.now();
    const result = parseManaboxCsvContent(csv);
    const elapsed = performance.now() - t0;

    expect(result.cards.length).toBeGreaterThan(12_000);
    expect(elapsed).toBeLessThan(2_000);
  });
});
